// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cliReq.proto

package org.bro.lssrv.pb;

public final class CliRequst {
  private CliRequst() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lspb.ClientMsgType}
   */
  public enum ClientMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** default 
     * </pre>
     *
     * <code>errorClientType = 0;</code>
     */
    errorClientType(0),
    /**
     * <pre>
     ** 进入游戏 
     * </pre>
     *
     * <code>cliEnterRoom = 101;</code>
     */
    cliEnterRoom(101),
    /**
     * <pre>
     ** 通知服务器初始化完成 
     * </pre>
     *
     * <code>cliInitOver = 102;</code>
     */
    cliInitOver(102),
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>cliOperate = 103;</code>
     */
    cliOperate(103),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** default 
     * </pre>
     *
     * <code>errorClientType = 0;</code>
     */
    public static final int errorClientType_VALUE = 0;
    /**
     * <pre>
     ** 进入游戏 
     * </pre>
     *
     * <code>cliEnterRoom = 101;</code>
     */
    public static final int cliEnterRoom_VALUE = 101;
    /**
     * <pre>
     ** 通知服务器初始化完成 
     * </pre>
     *
     * <code>cliInitOver = 102;</code>
     */
    public static final int cliInitOver_VALUE = 102;
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>cliOperate = 103;</code>
     */
    public static final int cliOperate_VALUE = 103;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ClientMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static ClientMsgType forNumber(int value) {
      switch (value) {
        case 0: return errorClientType;
        case 101: return cliEnterRoom;
        case 102: return cliInitOver;
        case 103: return cliOperate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientMsgType>() {
            public ClientMsgType findValueByNumber(int number) {
              return ClientMsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CliRequst.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientMsgType[] VALUES = values();

    public static ClientMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClientMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lspb.ClientMsgType)
  }

  public interface CliReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lspb.CliReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 用户名 
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <pre>
     ** 请求模块 
     * </pre>
     *
     * <code>.lspb.ModuleId moduleId = 2;</code>
     */
    int getModuleIdValue();
    /**
     * <pre>
     ** 请求模块 
     * </pre>
     *
     * <code>.lspb.ModuleId moduleId = 2;</code>
     */
    LsEnum.ModuleId getModuleId();

    /**
     * <pre>
     ** 请求方法名 
     * </pre>
     *
     * <code>.lspb.ClientMsgType methodId = 3;</code>
     */
    int getMethodIdValue();
    /**
     * <pre>
     ** 请求方法名 
     * </pre>
     *
     * <code>.lspb.ClientMsgType methodId = 3;</code>
     */
    ClientMsgType getMethodId();

    /**
     * <pre>
     ** 进入房间 
     * </pre>
     *
     * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
     */
    boolean hasCliEnterRoom();
    /**
     * <pre>
     ** 进入房间 
     * </pre>
     *
     * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
     */
    GameProto.CliEnterRoom getCliEnterRoom();
    /**
     * <pre>
     ** 进入房间 
     * </pre>
     *
     * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
     */
    GameProto.CliEnterRoomOrBuilder getCliEnterRoomOrBuilder();

    /**
     * <pre>
     ** 客户端初始化完成 
     * </pre>
     *
     * <code>.lspb.CliInitOver cliInitOver = 102;</code>
     */
    boolean hasCliInitOver();
    /**
     * <pre>
     ** 客户端初始化完成 
     * </pre>
     *
     * <code>.lspb.CliInitOver cliInitOver = 102;</code>
     */
    GameProto.CliInitOver getCliInitOver();
    /**
     * <pre>
     ** 客户端初始化完成 
     * </pre>
     *
     * <code>.lspb.CliInitOver cliInitOver = 102;</code>
     */
    GameProto.CliInitOverOrBuilder getCliInitOverOrBuilder();

    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>.lspb.CliOperate cliOperate = 103;</code>
     */
    boolean hasCliOperate();
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>.lspb.CliOperate cliOperate = 103;</code>
     */
    GameProto.CliOperate getCliOperate();
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>.lspb.CliOperate cliOperate = 103;</code>
     */
    GameProto.CliOperateOrBuilder getCliOperateOrBuilder();
  }
  /**
   * <pre>
   ** 所有上行请求都是clientRequest，服务器根据methodId读取具体的message内容,当 
   * </pre>
   *
   * Protobuf type {@code lspb.CliReq}
   */
  public  static final class CliReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lspb.CliReq)
      CliReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CliReq.newBuilder() to construct.
    private CliReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CliReq() {
      userId_ = 0;
      moduleId_ = 0;
      methodId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CliReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              moduleId_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              methodId_ = rawValue;
              break;
            }
            case 810: {
              GameProto.CliEnterRoom.Builder subBuilder = null;
              if (cliEnterRoom_ != null) {
                subBuilder = cliEnterRoom_.toBuilder();
              }
              cliEnterRoom_ = input.readMessage(GameProto.CliEnterRoom.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cliEnterRoom_);
                cliEnterRoom_ = subBuilder.buildPartial();
              }

              break;
            }
            case 818: {
              GameProto.CliInitOver.Builder subBuilder = null;
              if (cliInitOver_ != null) {
                subBuilder = cliInitOver_.toBuilder();
              }
              cliInitOver_ = input.readMessage(GameProto.CliInitOver.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cliInitOver_);
                cliInitOver_ = subBuilder.buildPartial();
              }

              break;
            }
            case 826: {
              GameProto.CliOperate.Builder subBuilder = null;
              if (cliOperate_ != null) {
                subBuilder = cliOperate_.toBuilder();
              }
              cliOperate_ = input.readMessage(GameProto.CliOperate.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cliOperate_);
                cliOperate_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CliRequst.internal_static_lspb_CliReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CliRequst.internal_static_lspb_CliReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CliReq.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <pre>
     ** 用户名 
     * </pre>
     *
     * <code>int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int MODULEID_FIELD_NUMBER = 2;
    private int moduleId_;
    /**
     * <pre>
     ** 请求模块 
     * </pre>
     *
     * <code>.lspb.ModuleId moduleId = 2;</code>
     */
    public int getModuleIdValue() {
      return moduleId_;
    }
    /**
     * <pre>
     ** 请求模块 
     * </pre>
     *
     * <code>.lspb.ModuleId moduleId = 2;</code>
     */
    public LsEnum.ModuleId getModuleId() {
      LsEnum.ModuleId result = LsEnum.ModuleId.valueOf(moduleId_);
      return result == null ? LsEnum.ModuleId.UNRECOGNIZED : result;
    }

    public static final int METHODID_FIELD_NUMBER = 3;
    private int methodId_;
    /**
     * <pre>
     ** 请求方法名 
     * </pre>
     *
     * <code>.lspb.ClientMsgType methodId = 3;</code>
     */
    public int getMethodIdValue() {
      return methodId_;
    }
    /**
     * <pre>
     ** 请求方法名 
     * </pre>
     *
     * <code>.lspb.ClientMsgType methodId = 3;</code>
     */
    public ClientMsgType getMethodId() {
      ClientMsgType result = ClientMsgType.valueOf(methodId_);
      return result == null ? ClientMsgType.UNRECOGNIZED : result;
    }

    public static final int CLIENTERROOM_FIELD_NUMBER = 101;
    private GameProto.CliEnterRoom cliEnterRoom_;
    /**
     * <pre>
     ** 进入房间 
     * </pre>
     *
     * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
     */
    public boolean hasCliEnterRoom() {
      return cliEnterRoom_ != null;
    }
    /**
     * <pre>
     ** 进入房间 
     * </pre>
     *
     * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
     */
    public GameProto.CliEnterRoom getCliEnterRoom() {
      return cliEnterRoom_ == null ? GameProto.CliEnterRoom.getDefaultInstance() : cliEnterRoom_;
    }
    /**
     * <pre>
     ** 进入房间 
     * </pre>
     *
     * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
     */
    public GameProto.CliEnterRoomOrBuilder getCliEnterRoomOrBuilder() {
      return getCliEnterRoom();
    }

    public static final int CLIINITOVER_FIELD_NUMBER = 102;
    private GameProto.CliInitOver cliInitOver_;
    /**
     * <pre>
     ** 客户端初始化完成 
     * </pre>
     *
     * <code>.lspb.CliInitOver cliInitOver = 102;</code>
     */
    public boolean hasCliInitOver() {
      return cliInitOver_ != null;
    }
    /**
     * <pre>
     ** 客户端初始化完成 
     * </pre>
     *
     * <code>.lspb.CliInitOver cliInitOver = 102;</code>
     */
    public GameProto.CliInitOver getCliInitOver() {
      return cliInitOver_ == null ? GameProto.CliInitOver.getDefaultInstance() : cliInitOver_;
    }
    /**
     * <pre>
     ** 客户端初始化完成 
     * </pre>
     *
     * <code>.lspb.CliInitOver cliInitOver = 102;</code>
     */
    public GameProto.CliInitOverOrBuilder getCliInitOverOrBuilder() {
      return getCliInitOver();
    }

    public static final int CLIOPERATE_FIELD_NUMBER = 103;
    private GameProto.CliOperate cliOperate_;
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>.lspb.CliOperate cliOperate = 103;</code>
     */
    public boolean hasCliOperate() {
      return cliOperate_ != null;
    }
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>.lspb.CliOperate cliOperate = 103;</code>
     */
    public GameProto.CliOperate getCliOperate() {
      return cliOperate_ == null ? GameProto.CliOperate.getDefaultInstance() : cliOperate_;
    }
    /**
     * <pre>
     ** 客户端对坦克的具体操作 
     * </pre>
     *
     * <code>.lspb.CliOperate cliOperate = 103;</code>
     */
    public GameProto.CliOperateOrBuilder getCliOperateOrBuilder() {
      return getCliOperate();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (moduleId_ != LsEnum.ModuleId.UnknownModel.getNumber()) {
        output.writeEnum(2, moduleId_);
      }
      if (methodId_ != ClientMsgType.errorClientType.getNumber()) {
        output.writeEnum(3, methodId_);
      }
      if (cliEnterRoom_ != null) {
        output.writeMessage(101, getCliEnterRoom());
      }
      if (cliInitOver_ != null) {
        output.writeMessage(102, getCliInitOver());
      }
      if (cliOperate_ != null) {
        output.writeMessage(103, getCliOperate());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (moduleId_ != LsEnum.ModuleId.UnknownModel.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, moduleId_);
      }
      if (methodId_ != ClientMsgType.errorClientType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, methodId_);
      }
      if (cliEnterRoom_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, getCliEnterRoom());
      }
      if (cliInitOver_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, getCliInitOver());
      }
      if (cliOperate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(103, getCliOperate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CliReq)) {
        return super.equals(obj);
      }
      CliReq other = (CliReq) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && moduleId_ == other.moduleId_;
      result = result && methodId_ == other.methodId_;
      result = result && (hasCliEnterRoom() == other.hasCliEnterRoom());
      if (hasCliEnterRoom()) {
        result = result && getCliEnterRoom()
            .equals(other.getCliEnterRoom());
      }
      result = result && (hasCliInitOver() == other.hasCliInitOver());
      if (hasCliInitOver()) {
        result = result && getCliInitOver()
            .equals(other.getCliInitOver());
      }
      result = result && (hasCliOperate() == other.hasCliOperate());
      if (hasCliOperate()) {
        result = result && getCliOperate()
            .equals(other.getCliOperate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + MODULEID_FIELD_NUMBER;
      hash = (53 * hash) + moduleId_;
      hash = (37 * hash) + METHODID_FIELD_NUMBER;
      hash = (53 * hash) + methodId_;
      if (hasCliEnterRoom()) {
        hash = (37 * hash) + CLIENTERROOM_FIELD_NUMBER;
        hash = (53 * hash) + getCliEnterRoom().hashCode();
      }
      if (hasCliInitOver()) {
        hash = (37 * hash) + CLIINITOVER_FIELD_NUMBER;
        hash = (53 * hash) + getCliInitOver().hashCode();
      }
      if (hasCliOperate()) {
        hash = (37 * hash) + CLIOPERATE_FIELD_NUMBER;
        hash = (53 * hash) + getCliOperate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CliReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CliReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CliReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CliReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CliReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CliReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CliReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CliReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CliReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CliReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CliReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CliReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CliReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 所有上行请求都是clientRequest，服务器根据methodId读取具体的message内容,当 
     * </pre>
     *
     * Protobuf type {@code lspb.CliReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lspb.CliReq)
        CliReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CliRequst.internal_static_lspb_CliReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CliRequst.internal_static_lspb_CliReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CliReq.class, Builder.class);
      }

      // Construct using org.bro.lssrv.pb.CliRequst.CliReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0;

        moduleId_ = 0;

        methodId_ = 0;

        if (cliEnterRoomBuilder_ == null) {
          cliEnterRoom_ = null;
        } else {
          cliEnterRoom_ = null;
          cliEnterRoomBuilder_ = null;
        }
        if (cliInitOverBuilder_ == null) {
          cliInitOver_ = null;
        } else {
          cliInitOver_ = null;
          cliInitOverBuilder_ = null;
        }
        if (cliOperateBuilder_ == null) {
          cliOperate_ = null;
        } else {
          cliOperate_ = null;
          cliOperateBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CliRequst.internal_static_lspb_CliReq_descriptor;
      }

      public CliReq getDefaultInstanceForType() {
        return CliReq.getDefaultInstance();
      }

      public CliReq build() {
        CliReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CliReq buildPartial() {
        CliReq result = new CliReq(this);
        result.userId_ = userId_;
        result.moduleId_ = moduleId_;
        result.methodId_ = methodId_;
        if (cliEnterRoomBuilder_ == null) {
          result.cliEnterRoom_ = cliEnterRoom_;
        } else {
          result.cliEnterRoom_ = cliEnterRoomBuilder_.build();
        }
        if (cliInitOverBuilder_ == null) {
          result.cliInitOver_ = cliInitOver_;
        } else {
          result.cliInitOver_ = cliInitOverBuilder_.build();
        }
        if (cliOperateBuilder_ == null) {
          result.cliOperate_ = cliOperate_;
        } else {
          result.cliOperate_ = cliOperateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CliReq) {
          return mergeFrom((CliReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CliReq other) {
        if (other == CliReq.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.moduleId_ != 0) {
          setModuleIdValue(other.getModuleIdValue());
        }
        if (other.methodId_ != 0) {
          setMethodIdValue(other.getMethodIdValue());
        }
        if (other.hasCliEnterRoom()) {
          mergeCliEnterRoom(other.getCliEnterRoom());
        }
        if (other.hasCliInitOver()) {
          mergeCliInitOver(other.getCliInitOver());
        }
        if (other.hasCliOperate()) {
          mergeCliOperate(other.getCliOperate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CliReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CliReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       ** 用户名 
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       ** 用户名 
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 用户名 
       * </pre>
       *
       * <code>int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int moduleId_ = 0;
      /**
       * <pre>
       ** 请求模块 
       * </pre>
       *
       * <code>.lspb.ModuleId moduleId = 2;</code>
       */
      public int getModuleIdValue() {
        return moduleId_;
      }
      /**
       * <pre>
       ** 请求模块 
       * </pre>
       *
       * <code>.lspb.ModuleId moduleId = 2;</code>
       */
      public Builder setModuleIdValue(int value) {
        moduleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 请求模块 
       * </pre>
       *
       * <code>.lspb.ModuleId moduleId = 2;</code>
       */
      public LsEnum.ModuleId getModuleId() {
        LsEnum.ModuleId result = LsEnum.ModuleId.valueOf(moduleId_);
        return result == null ? LsEnum.ModuleId.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       ** 请求模块 
       * </pre>
       *
       * <code>.lspb.ModuleId moduleId = 2;</code>
       */
      public Builder setModuleId(LsEnum.ModuleId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        moduleId_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 请求模块 
       * </pre>
       *
       * <code>.lspb.ModuleId moduleId = 2;</code>
       */
      public Builder clearModuleId() {
        
        moduleId_ = 0;
        onChanged();
        return this;
      }

      private int methodId_ = 0;
      /**
       * <pre>
       ** 请求方法名 
       * </pre>
       *
       * <code>.lspb.ClientMsgType methodId = 3;</code>
       */
      public int getMethodIdValue() {
        return methodId_;
      }
      /**
       * <pre>
       ** 请求方法名 
       * </pre>
       *
       * <code>.lspb.ClientMsgType methodId = 3;</code>
       */
      public Builder setMethodIdValue(int value) {
        methodId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 请求方法名 
       * </pre>
       *
       * <code>.lspb.ClientMsgType methodId = 3;</code>
       */
      public ClientMsgType getMethodId() {
        ClientMsgType result = ClientMsgType.valueOf(methodId_);
        return result == null ? ClientMsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       ** 请求方法名 
       * </pre>
       *
       * <code>.lspb.ClientMsgType methodId = 3;</code>
       */
      public Builder setMethodId(ClientMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        methodId_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 请求方法名 
       * </pre>
       *
       * <code>.lspb.ClientMsgType methodId = 3;</code>
       */
      public Builder clearMethodId() {
        
        methodId_ = 0;
        onChanged();
        return this;
      }

      private GameProto.CliEnterRoom cliEnterRoom_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.CliEnterRoom, GameProto.CliEnterRoom.Builder, GameProto.CliEnterRoomOrBuilder> cliEnterRoomBuilder_;
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public boolean hasCliEnterRoom() {
        return cliEnterRoomBuilder_ != null || cliEnterRoom_ != null;
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public GameProto.CliEnterRoom getCliEnterRoom() {
        if (cliEnterRoomBuilder_ == null) {
          return cliEnterRoom_ == null ? GameProto.CliEnterRoom.getDefaultInstance() : cliEnterRoom_;
        } else {
          return cliEnterRoomBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public Builder setCliEnterRoom(GameProto.CliEnterRoom value) {
        if (cliEnterRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cliEnterRoom_ = value;
          onChanged();
        } else {
          cliEnterRoomBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public Builder setCliEnterRoom(
          GameProto.CliEnterRoom.Builder builderForValue) {
        if (cliEnterRoomBuilder_ == null) {
          cliEnterRoom_ = builderForValue.build();
          onChanged();
        } else {
          cliEnterRoomBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public Builder mergeCliEnterRoom(GameProto.CliEnterRoom value) {
        if (cliEnterRoomBuilder_ == null) {
          if (cliEnterRoom_ != null) {
            cliEnterRoom_ =
              GameProto.CliEnterRoom.newBuilder(cliEnterRoom_).mergeFrom(value).buildPartial();
          } else {
            cliEnterRoom_ = value;
          }
          onChanged();
        } else {
          cliEnterRoomBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public Builder clearCliEnterRoom() {
        if (cliEnterRoomBuilder_ == null) {
          cliEnterRoom_ = null;
          onChanged();
        } else {
          cliEnterRoom_ = null;
          cliEnterRoomBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public GameProto.CliEnterRoom.Builder getCliEnterRoomBuilder() {
        
        onChanged();
        return getCliEnterRoomFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      public GameProto.CliEnterRoomOrBuilder getCliEnterRoomOrBuilder() {
        if (cliEnterRoomBuilder_ != null) {
          return cliEnterRoomBuilder_.getMessageOrBuilder();
        } else {
          return cliEnterRoom_ == null ?
              GameProto.CliEnterRoom.getDefaultInstance() : cliEnterRoom_;
        }
      }
      /**
       * <pre>
       ** 进入房间 
       * </pre>
       *
       * <code>.lspb.CliEnterRoom cliEnterRoom = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.CliEnterRoom, GameProto.CliEnterRoom.Builder, GameProto.CliEnterRoomOrBuilder>
          getCliEnterRoomFieldBuilder() {
        if (cliEnterRoomBuilder_ == null) {
          cliEnterRoomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.CliEnterRoom, GameProto.CliEnterRoom.Builder, GameProto.CliEnterRoomOrBuilder>(
                  getCliEnterRoom(),
                  getParentForChildren(),
                  isClean());
          cliEnterRoom_ = null;
        }
        return cliEnterRoomBuilder_;
      }

      private GameProto.CliInitOver cliInitOver_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.CliInitOver, GameProto.CliInitOver.Builder, GameProto.CliInitOverOrBuilder> cliInitOverBuilder_;
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public boolean hasCliInitOver() {
        return cliInitOverBuilder_ != null || cliInitOver_ != null;
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public GameProto.CliInitOver getCliInitOver() {
        if (cliInitOverBuilder_ == null) {
          return cliInitOver_ == null ? GameProto.CliInitOver.getDefaultInstance() : cliInitOver_;
        } else {
          return cliInitOverBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public Builder setCliInitOver(GameProto.CliInitOver value) {
        if (cliInitOverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cliInitOver_ = value;
          onChanged();
        } else {
          cliInitOverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public Builder setCliInitOver(
          GameProto.CliInitOver.Builder builderForValue) {
        if (cliInitOverBuilder_ == null) {
          cliInitOver_ = builderForValue.build();
          onChanged();
        } else {
          cliInitOverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public Builder mergeCliInitOver(GameProto.CliInitOver value) {
        if (cliInitOverBuilder_ == null) {
          if (cliInitOver_ != null) {
            cliInitOver_ =
              GameProto.CliInitOver.newBuilder(cliInitOver_).mergeFrom(value).buildPartial();
          } else {
            cliInitOver_ = value;
          }
          onChanged();
        } else {
          cliInitOverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public Builder clearCliInitOver() {
        if (cliInitOverBuilder_ == null) {
          cliInitOver_ = null;
          onChanged();
        } else {
          cliInitOver_ = null;
          cliInitOverBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public GameProto.CliInitOver.Builder getCliInitOverBuilder() {
        
        onChanged();
        return getCliInitOverFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      public GameProto.CliInitOverOrBuilder getCliInitOverOrBuilder() {
        if (cliInitOverBuilder_ != null) {
          return cliInitOverBuilder_.getMessageOrBuilder();
        } else {
          return cliInitOver_ == null ?
              GameProto.CliInitOver.getDefaultInstance() : cliInitOver_;
        }
      }
      /**
       * <pre>
       ** 客户端初始化完成 
       * </pre>
       *
       * <code>.lspb.CliInitOver cliInitOver = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.CliInitOver, GameProto.CliInitOver.Builder, GameProto.CliInitOverOrBuilder>
          getCliInitOverFieldBuilder() {
        if (cliInitOverBuilder_ == null) {
          cliInitOverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.CliInitOver, GameProto.CliInitOver.Builder, GameProto.CliInitOverOrBuilder>(
                  getCliInitOver(),
                  getParentForChildren(),
                  isClean());
          cliInitOver_ = null;
        }
        return cliInitOverBuilder_;
      }

      private GameProto.CliOperate cliOperate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.CliOperate, GameProto.CliOperate.Builder, GameProto.CliOperateOrBuilder> cliOperateBuilder_;
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public boolean hasCliOperate() {
        return cliOperateBuilder_ != null || cliOperate_ != null;
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public GameProto.CliOperate getCliOperate() {
        if (cliOperateBuilder_ == null) {
          return cliOperate_ == null ? GameProto.CliOperate.getDefaultInstance() : cliOperate_;
        } else {
          return cliOperateBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public Builder setCliOperate(GameProto.CliOperate value) {
        if (cliOperateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cliOperate_ = value;
          onChanged();
        } else {
          cliOperateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public Builder setCliOperate(
          GameProto.CliOperate.Builder builderForValue) {
        if (cliOperateBuilder_ == null) {
          cliOperate_ = builderForValue.build();
          onChanged();
        } else {
          cliOperateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public Builder mergeCliOperate(GameProto.CliOperate value) {
        if (cliOperateBuilder_ == null) {
          if (cliOperate_ != null) {
            cliOperate_ =
              GameProto.CliOperate.newBuilder(cliOperate_).mergeFrom(value).buildPartial();
          } else {
            cliOperate_ = value;
          }
          onChanged();
        } else {
          cliOperateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public Builder clearCliOperate() {
        if (cliOperateBuilder_ == null) {
          cliOperate_ = null;
          onChanged();
        } else {
          cliOperate_ = null;
          cliOperateBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public GameProto.CliOperate.Builder getCliOperateBuilder() {
        
        onChanged();
        return getCliOperateFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      public GameProto.CliOperateOrBuilder getCliOperateOrBuilder() {
        if (cliOperateBuilder_ != null) {
          return cliOperateBuilder_.getMessageOrBuilder();
        } else {
          return cliOperate_ == null ?
              GameProto.CliOperate.getDefaultInstance() : cliOperate_;
        }
      }
      /**
       * <pre>
       ** 客户端对坦克的具体操作 
       * </pre>
       *
       * <code>.lspb.CliOperate cliOperate = 103;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.CliOperate, GameProto.CliOperate.Builder, GameProto.CliOperateOrBuilder>
          getCliOperateFieldBuilder() {
        if (cliOperateBuilder_ == null) {
          cliOperateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.CliOperate, GameProto.CliOperate.Builder, GameProto.CliOperateOrBuilder>(
                  getCliOperate(),
                  getParentForChildren(),
                  isClean());
          cliOperate_ = null;
        }
        return cliOperateBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lspb.CliReq)
    }

    // @@protoc_insertion_point(class_scope:lspb.CliReq)
    private static final CliReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CliReq();
    }

    public static CliReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CliReq>
        PARSER = new com.google.protobuf.AbstractParser<CliReq>() {
      public CliReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CliReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CliReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CliReq> getParserForType() {
      return PARSER;
    }

    public CliReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lspb_CliReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lspb_CliReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014cliReq.proto\022\004lspb\032\014lsEnum.proto\032\017game" +
      "Proto.proto\"\331\001\n\006CliReq\022\016\n\006userId\030\001 \001(\005\022 " +
      "\n\010moduleId\030\002 \001(\0162\016.lspb.ModuleId\022%\n\010meth" +
      "odId\030\003 \001(\0162\023.lspb.ClientMsgType\022(\n\014cliEn" +
      "terRoom\030e \001(\0132\022.lspb.CliEnterRoom\022&\n\013cli" +
      "InitOver\030f \001(\0132\021.lspb.CliInitOver\022$\n\ncli" +
      "Operate\030g \001(\0132\020.lspb.CliOperate*W\n\rClien" +
      "tMsgType\022\023\n\017errorClientType\020\000\022\020\n\014cliEnte" +
      "rRoom\020e\022\017\n\013cliInitOver\020f\022\016\n\ncliOperate\020g" +
      "B\035\n\020org.bro.lssrv.pbB\tCliRequstb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          LsEnum.getDescriptor(),
          GameProto.getDescriptor(),
        }, assigner);
    internal_static_lspb_CliReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lspb_CliReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lspb_CliReq_descriptor,
        new String[] { "UserId", "ModuleId", "MethodId", "CliEnterRoom", "CliInitOver", "CliOperate", });
    LsEnum.getDescriptor();
    GameProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
