// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lsEnum.proto

package org.bro.lssrv.pb;

public final class LsEnum {
  private LsEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lspb.ModuleId}
   */
  public enum ModuleId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** default 
     * </pre>
     *
     * <code>UnknownModel = 0;</code>
     */
    UnknownModel(0),
    /**
     * <pre>
     ** game 
     * </pre>
     *
     * <code>Game = 1;</code>
     */
    Game(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** default 
     * </pre>
     *
     * <code>UnknownModel = 0;</code>
     */
    public static final int UnknownModel_VALUE = 0;
    /**
     * <pre>
     ** game 
     * </pre>
     *
     * <code>Game = 1;</code>
     */
    public static final int Game_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ModuleId valueOf(int value) {
      return forNumber(value);
    }

    public static ModuleId forNumber(int value) {
      switch (value) {
        case 0: return UnknownModel;
        case 1: return Game;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ModuleId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ModuleId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModuleId>() {
            public ModuleId findValueByNumber(int number) {
              return ModuleId.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LsEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final ModuleId[] VALUES = values();

    public static ModuleId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ModuleId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lspb.ModuleId)
  }

  /**
   * Protobuf enum {@code lspb.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** 成功 
     * </pre>
     *
     * <code>success = 0;</code>
     */
    success(0),
    /**
     * <pre>
     ** 任意失败 
     * </pre>
     *
     * <code>err = 1;</code>
     */
    err(1),
    /**
     * <pre>
     ** 没有该方法错误 
     * </pre>
     *
     * <code>errNoMethod = 2;</code>
     */
    errNoMethod(2),
    /**
     * <pre>
     ** 消息为空 
     * </pre>
     *
     * <code>errNulMsg = 3;</code>
     */
    errNulMsg(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** 成功 
     * </pre>
     *
     * <code>success = 0;</code>
     */
    public static final int success_VALUE = 0;
    /**
     * <pre>
     ** 任意失败 
     * </pre>
     *
     * <code>err = 1;</code>
     */
    public static final int err_VALUE = 1;
    /**
     * <pre>
     ** 没有该方法错误 
     * </pre>
     *
     * <code>errNoMethod = 2;</code>
     */
    public static final int errNoMethod_VALUE = 2;
    /**
     * <pre>
     ** 消息为空 
     * </pre>
     *
     * <code>errNulMsg = 3;</code>
     */
    public static final int errNulMsg_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    public static Result forNumber(int value) {
      switch (value) {
        case 0: return success;
        case 1: return err;
        case 2: return errNoMethod;
        case 3: return errNulMsg;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LsEnum.getDescriptor().getEnumTypes().get(1);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lspb.Result)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014lsEnum.proto\022\004lspb*&\n\010ModuleId\022\020\n\014Unkn" +
      "ownModel\020\000\022\010\n\004Game\020\001*>\n\006Result\022\013\n\007succes" +
      "s\020\000\022\007\n\003err\020\001\022\017\n\013errNoMethod\020\002\022\r\n\terrNulM" +
      "sg\020\003B\022\n\020org.bro.lssrv.pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
