// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srvRes.proto

package org.bro.lssrv.pb;

public final class SrvResponse {
  private SrvResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lspb.SrvMsgType}
   */
  public enum SrvMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** default 
     * </pre>
     *
     * <code>errorServerType = 0;</code>
     */
    errorServerType(0),
    /**
     * <pre>
     ** 进入游戏 
     * </pre>
     *
     * <code>srvEnterRoom = 101;</code>
     */
    srvEnterRoom(101),
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>srvInitOver = 102;</code>
     */
    srvInitOver(102),
    /**
     * <pre>
     ** 房间初始化 
     * </pre>
     *
     * <code>bGameInit = 1001;</code>
     */
    bGameInit(1001),
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>bGameStart = 1002;</code>
     */
    bGameStart(1002),
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>bGameFrame = 1003;</code>
     */
    bGameFrame(1003),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** default 
     * </pre>
     *
     * <code>errorServerType = 0;</code>
     */
    public static final int errorServerType_VALUE = 0;
    /**
     * <pre>
     ** 进入游戏 
     * </pre>
     *
     * <code>srvEnterRoom = 101;</code>
     */
    public static final int srvEnterRoom_VALUE = 101;
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>srvInitOver = 102;</code>
     */
    public static final int srvInitOver_VALUE = 102;
    /**
     * <pre>
     ** 房间初始化 
     * </pre>
     *
     * <code>bGameInit = 1001;</code>
     */
    public static final int bGameInit_VALUE = 1001;
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>bGameStart = 1002;</code>
     */
    public static final int bGameStart_VALUE = 1002;
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>bGameFrame = 1003;</code>
     */
    public static final int bGameFrame_VALUE = 1003;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SrvMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static SrvMsgType forNumber(int value) {
      switch (value) {
        case 0: return errorServerType;
        case 101: return srvEnterRoom;
        case 102: return srvInitOver;
        case 1001: return bGameInit;
        case 1002: return bGameStart;
        case 1003: return bGameFrame;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SrvMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SrvMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SrvMsgType>() {
            public SrvMsgType findValueByNumber(int number) {
              return SrvMsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SrvResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final SrvMsgType[] VALUES = values();

    public static SrvMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SrvMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lspb.SrvMsgType)
  }

  public interface SrvResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lspb.SrvRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 返回方法名 
     * </pre>
     *
     * <code>.lspb.SrvMsgType methodId = 1;</code>
     */
    int getMethodIdValue();
    /**
     * <pre>
     ** 返回方法名 
     * </pre>
     *
     * <code>.lspb.SrvMsgType methodId = 1;</code>
     */
    SrvMsgType getMethodId();

    /**
     * <pre>
     ** 返回码，包含success和错误码 
     * </pre>
     *
     * <code>.lspb.Result result = 2;</code>
     */
    int getResultValue();
    /**
     * <pre>
     ** 返回码，包含success和错误码 
     * </pre>
     *
     * <code>.lspb.Result result = 2;</code>
     */
    LsEnum.Result getResult();

    /**
     * <pre>
     ** 错误展示字段，如果result不为0，则取该字段给用户展示 
     * </pre>
     *
     * <code>string errStr = 3;</code>
     */
    String getErrStr();
    /**
     * <pre>
     ** 错误展示字段，如果result不为0，则取该字段给用户展示 
     * </pre>
     *
     * <code>string errStr = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrStrBytes();

    /**
     * <pre>
     ** 玩家进入房间 
     * </pre>
     *
     * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
     */
    boolean hasSrvEnterRoom();
    /**
     * <pre>
     ** 玩家进入房间 
     * </pre>
     *
     * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
     */
    GameProto.SrvEnterRoom getSrvEnterRoom();
    /**
     * <pre>
     ** 玩家进入房间 
     * </pre>
     *
     * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
     */
    GameProto.SrvEnterRoomOrBuilder getSrvEnterRoomOrBuilder();

    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
     */
    boolean hasSrvInitOver();
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
     */
    GameProto.SrvInitOver getSrvInitOver();
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
     */
    GameProto.SrvInitOverOrBuilder getSrvInitOverOrBuilder();

    /**
     * <pre>
     ** 游戏初始化信息 
     * </pre>
     *
     * <code>.lspb.BGameInit bGameInit = 1001;</code>
     */
    boolean hasBGameInit();
    /**
     * <pre>
     ** 游戏初始化信息 
     * </pre>
     *
     * <code>.lspb.BGameInit bGameInit = 1001;</code>
     */
    GameProto.BGameInit getBGameInit();
    /**
     * <pre>
     ** 游戏初始化信息 
     * </pre>
     *
     * <code>.lspb.BGameInit bGameInit = 1001;</code>
     */
    GameProto.BGameInitOrBuilder getBGameInitOrBuilder();

    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>.lspb.BGameStart bGameStart = 1002;</code>
     */
    boolean hasBGameStart();
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>.lspb.BGameStart bGameStart = 1002;</code>
     */
    GameProto.BGameStart getBGameStart();
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>.lspb.BGameStart bGameStart = 1002;</code>
     */
    GameProto.BGameStartOrBuilder getBGameStartOrBuilder();

    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
     */
    boolean hasBGameFrame();
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
     */
    GameProto.BGameFrame getBGameFrame();
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
     */
    GameProto.BGameFrameOrBuilder getBGameFrameOrBuilder();
  }
  /**
   * <pre>
   ** 所有下行请求都是serverResponse，服务器会传递具体内容的标示methodId，客户端根据methodId进行处理 
   * </pre>
   *
   * Protobuf type {@code lspb.SrvRes}
   */
  public  static final class SrvRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:lspb.SrvRes)
      SrvResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SrvRes.newBuilder() to construct.
    private SrvRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SrvRes() {
      methodId_ = 0;
      result_ = 0;
      errStr_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SrvRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              methodId_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              errStr_ = s;
              break;
            }
            case 810: {
              GameProto.SrvEnterRoom.Builder subBuilder = null;
              if (srvEnterRoom_ != null) {
                subBuilder = srvEnterRoom_.toBuilder();
              }
              srvEnterRoom_ = input.readMessage(GameProto.SrvEnterRoom.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(srvEnterRoom_);
                srvEnterRoom_ = subBuilder.buildPartial();
              }

              break;
            }
            case 818: {
              GameProto.SrvInitOver.Builder subBuilder = null;
              if (srvInitOver_ != null) {
                subBuilder = srvInitOver_.toBuilder();
              }
              srvInitOver_ = input.readMessage(GameProto.SrvInitOver.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(srvInitOver_);
                srvInitOver_ = subBuilder.buildPartial();
              }

              break;
            }
            case 8010: {
              GameProto.BGameInit.Builder subBuilder = null;
              if (bGameInit_ != null) {
                subBuilder = bGameInit_.toBuilder();
              }
              bGameInit_ = input.readMessage(GameProto.BGameInit.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bGameInit_);
                bGameInit_ = subBuilder.buildPartial();
              }

              break;
            }
            case 8018: {
              GameProto.BGameStart.Builder subBuilder = null;
              if (bGameStart_ != null) {
                subBuilder = bGameStart_.toBuilder();
              }
              bGameStart_ = input.readMessage(GameProto.BGameStart.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bGameStart_);
                bGameStart_ = subBuilder.buildPartial();
              }

              break;
            }
            case 8026: {
              GameProto.BGameFrame.Builder subBuilder = null;
              if (bGameFrame_ != null) {
                subBuilder = bGameFrame_.toBuilder();
              }
              bGameFrame_ = input.readMessage(GameProto.BGameFrame.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bGameFrame_);
                bGameFrame_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SrvResponse.internal_static_lspb_SrvRes_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SrvResponse.internal_static_lspb_SrvRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SrvRes.class, Builder.class);
    }

    public static final int METHODID_FIELD_NUMBER = 1;
    private int methodId_;
    /**
     * <pre>
     ** 返回方法名 
     * </pre>
     *
     * <code>.lspb.SrvMsgType methodId = 1;</code>
     */
    public int getMethodIdValue() {
      return methodId_;
    }
    /**
     * <pre>
     ** 返回方法名 
     * </pre>
     *
     * <code>.lspb.SrvMsgType methodId = 1;</code>
     */
    public SrvMsgType getMethodId() {
      SrvMsgType result = SrvMsgType.valueOf(methodId_);
      return result == null ? SrvMsgType.UNRECOGNIZED : result;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <pre>
     ** 返回码，包含success和错误码 
     * </pre>
     *
     * <code>.lspb.Result result = 2;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <pre>
     ** 返回码，包含success和错误码 
     * </pre>
     *
     * <code>.lspb.Result result = 2;</code>
     */
    public LsEnum.Result getResult() {
      LsEnum.Result result = LsEnum.Result.valueOf(result_);
      return result == null ? LsEnum.Result.UNRECOGNIZED : result;
    }

    public static final int ERRSTR_FIELD_NUMBER = 3;
    private volatile Object errStr_;
    /**
     * <pre>
     ** 错误展示字段，如果result不为0，则取该字段给用户展示 
     * </pre>
     *
     * <code>string errStr = 3;</code>
     */
    public String getErrStr() {
      Object ref = errStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 错误展示字段，如果result不为0，则取该字段给用户展示 
     * </pre>
     *
     * <code>string errStr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrStrBytes() {
      Object ref = errStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRVENTERROOM_FIELD_NUMBER = 101;
    private GameProto.SrvEnterRoom srvEnterRoom_;
    /**
     * <pre>
     ** 玩家进入房间 
     * </pre>
     *
     * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
     */
    public boolean hasSrvEnterRoom() {
      return srvEnterRoom_ != null;
    }
    /**
     * <pre>
     ** 玩家进入房间 
     * </pre>
     *
     * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
     */
    public GameProto.SrvEnterRoom getSrvEnterRoom() {
      return srvEnterRoom_ == null ? GameProto.SrvEnterRoom.getDefaultInstance() : srvEnterRoom_;
    }
    /**
     * <pre>
     ** 玩家进入房间 
     * </pre>
     *
     * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
     */
    public GameProto.SrvEnterRoomOrBuilder getSrvEnterRoomOrBuilder() {
      return getSrvEnterRoom();
    }

    public static final int SRVINITOVER_FIELD_NUMBER = 102;
    private GameProto.SrvInitOver srvInitOver_;
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
     */
    public boolean hasSrvInitOver() {
      return srvInitOver_ != null;
    }
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
     */
    public GameProto.SrvInitOver getSrvInitOver() {
      return srvInitOver_ == null ? GameProto.SrvInitOver.getDefaultInstance() : srvInitOver_;
    }
    /**
     * <pre>
     ** 初始化完成ACK 
     * </pre>
     *
     * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
     */
    public GameProto.SrvInitOverOrBuilder getSrvInitOverOrBuilder() {
      return getSrvInitOver();
    }

    public static final int BGAMEINIT_FIELD_NUMBER = 1001;
    private GameProto.BGameInit bGameInit_;
    /**
     * <pre>
     ** 游戏初始化信息 
     * </pre>
     *
     * <code>.lspb.BGameInit bGameInit = 1001;</code>
     */
    public boolean hasBGameInit() {
      return bGameInit_ != null;
    }
    /**
     * <pre>
     ** 游戏初始化信息 
     * </pre>
     *
     * <code>.lspb.BGameInit bGameInit = 1001;</code>
     */
    public GameProto.BGameInit getBGameInit() {
      return bGameInit_ == null ? GameProto.BGameInit.getDefaultInstance() : bGameInit_;
    }
    /**
     * <pre>
     ** 游戏初始化信息 
     * </pre>
     *
     * <code>.lspb.BGameInit bGameInit = 1001;</code>
     */
    public GameProto.BGameInitOrBuilder getBGameInitOrBuilder() {
      return getBGameInit();
    }

    public static final int BGAMESTART_FIELD_NUMBER = 1002;
    private GameProto.BGameStart bGameStart_;
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>.lspb.BGameStart bGameStart = 1002;</code>
     */
    public boolean hasBGameStart() {
      return bGameStart_ != null;
    }
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>.lspb.BGameStart bGameStart = 1002;</code>
     */
    public GameProto.BGameStart getBGameStart() {
      return bGameStart_ == null ? GameProto.BGameStart.getDefaultInstance() : bGameStart_;
    }
    /**
     * <pre>
     ** 游戏正式开始推送 
     * </pre>
     *
     * <code>.lspb.BGameStart bGameStart = 1002;</code>
     */
    public GameProto.BGameStartOrBuilder getBGameStartOrBuilder() {
      return getBGameStart();
    }

    public static final int BGAMEFRAME_FIELD_NUMBER = 1003;
    private GameProto.BGameFrame bGameFrame_;
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
     */
    public boolean hasBGameFrame() {
      return bGameFrame_ != null;
    }
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
     */
    public GameProto.BGameFrame getBGameFrame() {
      return bGameFrame_ == null ? GameProto.BGameFrame.getDefaultInstance() : bGameFrame_;
    }
    /**
     * <pre>
     ** 游戏逻辑帧操作 
     * </pre>
     *
     * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
     */
    public GameProto.BGameFrameOrBuilder getBGameFrameOrBuilder() {
      return getBGameFrame();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (methodId_ != SrvMsgType.errorServerType.getNumber()) {
        output.writeEnum(1, methodId_);
      }
      if (result_ != LsEnum.Result.success.getNumber()) {
        output.writeEnum(2, result_);
      }
      if (!getErrStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errStr_);
      }
      if (srvEnterRoom_ != null) {
        output.writeMessage(101, getSrvEnterRoom());
      }
      if (srvInitOver_ != null) {
        output.writeMessage(102, getSrvInitOver());
      }
      if (bGameInit_ != null) {
        output.writeMessage(1001, getBGameInit());
      }
      if (bGameStart_ != null) {
        output.writeMessage(1002, getBGameStart());
      }
      if (bGameFrame_ != null) {
        output.writeMessage(1003, getBGameFrame());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (methodId_ != SrvMsgType.errorServerType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, methodId_);
      }
      if (result_ != LsEnum.Result.success.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, result_);
      }
      if (!getErrStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errStr_);
      }
      if (srvEnterRoom_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, getSrvEnterRoom());
      }
      if (srvInitOver_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, getSrvInitOver());
      }
      if (bGameInit_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1001, getBGameInit());
      }
      if (bGameStart_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1002, getBGameStart());
      }
      if (bGameFrame_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1003, getBGameFrame());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SrvRes)) {
        return super.equals(obj);
      }
      SrvRes other = (SrvRes) obj;

      boolean result = true;
      result = result && methodId_ == other.methodId_;
      result = result && result_ == other.result_;
      result = result && getErrStr()
          .equals(other.getErrStr());
      result = result && (hasSrvEnterRoom() == other.hasSrvEnterRoom());
      if (hasSrvEnterRoom()) {
        result = result && getSrvEnterRoom()
            .equals(other.getSrvEnterRoom());
      }
      result = result && (hasSrvInitOver() == other.hasSrvInitOver());
      if (hasSrvInitOver()) {
        result = result && getSrvInitOver()
            .equals(other.getSrvInitOver());
      }
      result = result && (hasBGameInit() == other.hasBGameInit());
      if (hasBGameInit()) {
        result = result && getBGameInit()
            .equals(other.getBGameInit());
      }
      result = result && (hasBGameStart() == other.hasBGameStart());
      if (hasBGameStart()) {
        result = result && getBGameStart()
            .equals(other.getBGameStart());
      }
      result = result && (hasBGameFrame() == other.hasBGameFrame());
      if (hasBGameFrame()) {
        result = result && getBGameFrame()
            .equals(other.getBGameFrame());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METHODID_FIELD_NUMBER;
      hash = (53 * hash) + methodId_;
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
      hash = (53 * hash) + getErrStr().hashCode();
      if (hasSrvEnterRoom()) {
        hash = (37 * hash) + SRVENTERROOM_FIELD_NUMBER;
        hash = (53 * hash) + getSrvEnterRoom().hashCode();
      }
      if (hasSrvInitOver()) {
        hash = (37 * hash) + SRVINITOVER_FIELD_NUMBER;
        hash = (53 * hash) + getSrvInitOver().hashCode();
      }
      if (hasBGameInit()) {
        hash = (37 * hash) + BGAMEINIT_FIELD_NUMBER;
        hash = (53 * hash) + getBGameInit().hashCode();
      }
      if (hasBGameStart()) {
        hash = (37 * hash) + BGAMESTART_FIELD_NUMBER;
        hash = (53 * hash) + getBGameStart().hashCode();
      }
      if (hasBGameFrame()) {
        hash = (37 * hash) + BGAMEFRAME_FIELD_NUMBER;
        hash = (53 * hash) + getBGameFrame().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SrvRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SrvRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SrvRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SrvRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SrvRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SrvRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SrvRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SrvRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SrvRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SrvRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SrvRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SrvRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SrvRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 所有下行请求都是serverResponse，服务器会传递具体内容的标示methodId，客户端根据methodId进行处理 
     * </pre>
     *
     * Protobuf type {@code lspb.SrvRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lspb.SrvRes)
        SrvResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SrvResponse.internal_static_lspb_SrvRes_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SrvResponse.internal_static_lspb_SrvRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SrvRes.class, Builder.class);
      }

      // Construct using org.bro.lssrv.pb.SrvResponse.SrvRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        methodId_ = 0;

        result_ = 0;

        errStr_ = "";

        if (srvEnterRoomBuilder_ == null) {
          srvEnterRoom_ = null;
        } else {
          srvEnterRoom_ = null;
          srvEnterRoomBuilder_ = null;
        }
        if (srvInitOverBuilder_ == null) {
          srvInitOver_ = null;
        } else {
          srvInitOver_ = null;
          srvInitOverBuilder_ = null;
        }
        if (bGameInitBuilder_ == null) {
          bGameInit_ = null;
        } else {
          bGameInit_ = null;
          bGameInitBuilder_ = null;
        }
        if (bGameStartBuilder_ == null) {
          bGameStart_ = null;
        } else {
          bGameStart_ = null;
          bGameStartBuilder_ = null;
        }
        if (bGameFrameBuilder_ == null) {
          bGameFrame_ = null;
        } else {
          bGameFrame_ = null;
          bGameFrameBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SrvResponse.internal_static_lspb_SrvRes_descriptor;
      }

      public SrvRes getDefaultInstanceForType() {
        return SrvRes.getDefaultInstance();
      }

      public SrvRes build() {
        SrvRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SrvRes buildPartial() {
        SrvRes result = new SrvRes(this);
        result.methodId_ = methodId_;
        result.result_ = result_;
        result.errStr_ = errStr_;
        if (srvEnterRoomBuilder_ == null) {
          result.srvEnterRoom_ = srvEnterRoom_;
        } else {
          result.srvEnterRoom_ = srvEnterRoomBuilder_.build();
        }
        if (srvInitOverBuilder_ == null) {
          result.srvInitOver_ = srvInitOver_;
        } else {
          result.srvInitOver_ = srvInitOverBuilder_.build();
        }
        if (bGameInitBuilder_ == null) {
          result.bGameInit_ = bGameInit_;
        } else {
          result.bGameInit_ = bGameInitBuilder_.build();
        }
        if (bGameStartBuilder_ == null) {
          result.bGameStart_ = bGameStart_;
        } else {
          result.bGameStart_ = bGameStartBuilder_.build();
        }
        if (bGameFrameBuilder_ == null) {
          result.bGameFrame_ = bGameFrame_;
        } else {
          result.bGameFrame_ = bGameFrameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SrvRes) {
          return mergeFrom((SrvRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SrvRes other) {
        if (other == SrvRes.getDefaultInstance()) return this;
        if (other.methodId_ != 0) {
          setMethodIdValue(other.getMethodIdValue());
        }
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (!other.getErrStr().isEmpty()) {
          errStr_ = other.errStr_;
          onChanged();
        }
        if (other.hasSrvEnterRoom()) {
          mergeSrvEnterRoom(other.getSrvEnterRoom());
        }
        if (other.hasSrvInitOver()) {
          mergeSrvInitOver(other.getSrvInitOver());
        }
        if (other.hasBGameInit()) {
          mergeBGameInit(other.getBGameInit());
        }
        if (other.hasBGameStart()) {
          mergeBGameStart(other.getBGameStart());
        }
        if (other.hasBGameFrame()) {
          mergeBGameFrame(other.getBGameFrame());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SrvRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SrvRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int methodId_ = 0;
      /**
       * <pre>
       ** 返回方法名 
       * </pre>
       *
       * <code>.lspb.SrvMsgType methodId = 1;</code>
       */
      public int getMethodIdValue() {
        return methodId_;
      }
      /**
       * <pre>
       ** 返回方法名 
       * </pre>
       *
       * <code>.lspb.SrvMsgType methodId = 1;</code>
       */
      public Builder setMethodIdValue(int value) {
        methodId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 返回方法名 
       * </pre>
       *
       * <code>.lspb.SrvMsgType methodId = 1;</code>
       */
      public SrvMsgType getMethodId() {
        SrvMsgType result = SrvMsgType.valueOf(methodId_);
        return result == null ? SrvMsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       ** 返回方法名 
       * </pre>
       *
       * <code>.lspb.SrvMsgType methodId = 1;</code>
       */
      public Builder setMethodId(SrvMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        methodId_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 返回方法名 
       * </pre>
       *
       * <code>.lspb.SrvMsgType methodId = 1;</code>
       */
      public Builder clearMethodId() {
        
        methodId_ = 0;
        onChanged();
        return this;
      }

      private int result_ = 0;
      /**
       * <pre>
       ** 返回码，包含success和错误码 
       * </pre>
       *
       * <code>.lspb.Result result = 2;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <pre>
       ** 返回码，包含success和错误码 
       * </pre>
       *
       * <code>.lspb.Result result = 2;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 返回码，包含success和错误码 
       * </pre>
       *
       * <code>.lspb.Result result = 2;</code>
       */
      public LsEnum.Result getResult() {
        LsEnum.Result result = LsEnum.Result.valueOf(result_);
        return result == null ? LsEnum.Result.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       ** 返回码，包含success和错误码 
       * </pre>
       *
       * <code>.lspb.Result result = 2;</code>
       */
      public Builder setResult(LsEnum.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 返回码，包含success和错误码 
       * </pre>
       *
       * <code>.lspb.Result result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private Object errStr_ = "";
      /**
       * <pre>
       ** 错误展示字段，如果result不为0，则取该字段给用户展示 
       * </pre>
       *
       * <code>string errStr = 3;</code>
       */
      public String getErrStr() {
        Object ref = errStr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       ** 错误展示字段，如果result不为0，则取该字段给用户展示 
       * </pre>
       *
       * <code>string errStr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrStrBytes() {
        Object ref = errStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 错误展示字段，如果result不为0，则取该字段给用户展示 
       * </pre>
       *
       * <code>string errStr = 3;</code>
       */
      public Builder setErrStr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 错误展示字段，如果result不为0，则取该字段给用户展示 
       * </pre>
       *
       * <code>string errStr = 3;</code>
       */
      public Builder clearErrStr() {
        
        errStr_ = getDefaultInstance().getErrStr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 错误展示字段，如果result不为0，则取该字段给用户展示 
       * </pre>
       *
       * <code>string errStr = 3;</code>
       */
      public Builder setErrStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errStr_ = value;
        onChanged();
        return this;
      }

      private GameProto.SrvEnterRoom srvEnterRoom_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.SrvEnterRoom, GameProto.SrvEnterRoom.Builder, GameProto.SrvEnterRoomOrBuilder> srvEnterRoomBuilder_;
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public boolean hasSrvEnterRoom() {
        return srvEnterRoomBuilder_ != null || srvEnterRoom_ != null;
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public GameProto.SrvEnterRoom getSrvEnterRoom() {
        if (srvEnterRoomBuilder_ == null) {
          return srvEnterRoom_ == null ? GameProto.SrvEnterRoom.getDefaultInstance() : srvEnterRoom_;
        } else {
          return srvEnterRoomBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public Builder setSrvEnterRoom(GameProto.SrvEnterRoom value) {
        if (srvEnterRoomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          srvEnterRoom_ = value;
          onChanged();
        } else {
          srvEnterRoomBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public Builder setSrvEnterRoom(
          GameProto.SrvEnterRoom.Builder builderForValue) {
        if (srvEnterRoomBuilder_ == null) {
          srvEnterRoom_ = builderForValue.build();
          onChanged();
        } else {
          srvEnterRoomBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public Builder mergeSrvEnterRoom(GameProto.SrvEnterRoom value) {
        if (srvEnterRoomBuilder_ == null) {
          if (srvEnterRoom_ != null) {
            srvEnterRoom_ =
              GameProto.SrvEnterRoom.newBuilder(srvEnterRoom_).mergeFrom(value).buildPartial();
          } else {
            srvEnterRoom_ = value;
          }
          onChanged();
        } else {
          srvEnterRoomBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public Builder clearSrvEnterRoom() {
        if (srvEnterRoomBuilder_ == null) {
          srvEnterRoom_ = null;
          onChanged();
        } else {
          srvEnterRoom_ = null;
          srvEnterRoomBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public GameProto.SrvEnterRoom.Builder getSrvEnterRoomBuilder() {
        
        onChanged();
        return getSrvEnterRoomFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      public GameProto.SrvEnterRoomOrBuilder getSrvEnterRoomOrBuilder() {
        if (srvEnterRoomBuilder_ != null) {
          return srvEnterRoomBuilder_.getMessageOrBuilder();
        } else {
          return srvEnterRoom_ == null ?
              GameProto.SrvEnterRoom.getDefaultInstance() : srvEnterRoom_;
        }
      }
      /**
       * <pre>
       ** 玩家进入房间 
       * </pre>
       *
       * <code>.lspb.SrvEnterRoom srvEnterRoom = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.SrvEnterRoom, GameProto.SrvEnterRoom.Builder, GameProto.SrvEnterRoomOrBuilder>
          getSrvEnterRoomFieldBuilder() {
        if (srvEnterRoomBuilder_ == null) {
          srvEnterRoomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.SrvEnterRoom, GameProto.SrvEnterRoom.Builder, GameProto.SrvEnterRoomOrBuilder>(
                  getSrvEnterRoom(),
                  getParentForChildren(),
                  isClean());
          srvEnterRoom_ = null;
        }
        return srvEnterRoomBuilder_;
      }

      private GameProto.SrvInitOver srvInitOver_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.SrvInitOver, GameProto.SrvInitOver.Builder, GameProto.SrvInitOverOrBuilder> srvInitOverBuilder_;
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public boolean hasSrvInitOver() {
        return srvInitOverBuilder_ != null || srvInitOver_ != null;
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public GameProto.SrvInitOver getSrvInitOver() {
        if (srvInitOverBuilder_ == null) {
          return srvInitOver_ == null ? GameProto.SrvInitOver.getDefaultInstance() : srvInitOver_;
        } else {
          return srvInitOverBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public Builder setSrvInitOver(GameProto.SrvInitOver value) {
        if (srvInitOverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          srvInitOver_ = value;
          onChanged();
        } else {
          srvInitOverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public Builder setSrvInitOver(
          GameProto.SrvInitOver.Builder builderForValue) {
        if (srvInitOverBuilder_ == null) {
          srvInitOver_ = builderForValue.build();
          onChanged();
        } else {
          srvInitOverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public Builder mergeSrvInitOver(GameProto.SrvInitOver value) {
        if (srvInitOverBuilder_ == null) {
          if (srvInitOver_ != null) {
            srvInitOver_ =
              GameProto.SrvInitOver.newBuilder(srvInitOver_).mergeFrom(value).buildPartial();
          } else {
            srvInitOver_ = value;
          }
          onChanged();
        } else {
          srvInitOverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public Builder clearSrvInitOver() {
        if (srvInitOverBuilder_ == null) {
          srvInitOver_ = null;
          onChanged();
        } else {
          srvInitOver_ = null;
          srvInitOverBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public GameProto.SrvInitOver.Builder getSrvInitOverBuilder() {
        
        onChanged();
        return getSrvInitOverFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      public GameProto.SrvInitOverOrBuilder getSrvInitOverOrBuilder() {
        if (srvInitOverBuilder_ != null) {
          return srvInitOverBuilder_.getMessageOrBuilder();
        } else {
          return srvInitOver_ == null ?
              GameProto.SrvInitOver.getDefaultInstance() : srvInitOver_;
        }
      }
      /**
       * <pre>
       ** 初始化完成ACK 
       * </pre>
       *
       * <code>.lspb.SrvInitOver srvInitOver = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.SrvInitOver, GameProto.SrvInitOver.Builder, GameProto.SrvInitOverOrBuilder>
          getSrvInitOverFieldBuilder() {
        if (srvInitOverBuilder_ == null) {
          srvInitOverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.SrvInitOver, GameProto.SrvInitOver.Builder, GameProto.SrvInitOverOrBuilder>(
                  getSrvInitOver(),
                  getParentForChildren(),
                  isClean());
          srvInitOver_ = null;
        }
        return srvInitOverBuilder_;
      }

      private GameProto.BGameInit bGameInit_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.BGameInit, GameProto.BGameInit.Builder, GameProto.BGameInitOrBuilder> bGameInitBuilder_;
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public boolean hasBGameInit() {
        return bGameInitBuilder_ != null || bGameInit_ != null;
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public GameProto.BGameInit getBGameInit() {
        if (bGameInitBuilder_ == null) {
          return bGameInit_ == null ? GameProto.BGameInit.getDefaultInstance() : bGameInit_;
        } else {
          return bGameInitBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public Builder setBGameInit(GameProto.BGameInit value) {
        if (bGameInitBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bGameInit_ = value;
          onChanged();
        } else {
          bGameInitBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public Builder setBGameInit(
          GameProto.BGameInit.Builder builderForValue) {
        if (bGameInitBuilder_ == null) {
          bGameInit_ = builderForValue.build();
          onChanged();
        } else {
          bGameInitBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public Builder mergeBGameInit(GameProto.BGameInit value) {
        if (bGameInitBuilder_ == null) {
          if (bGameInit_ != null) {
            bGameInit_ =
              GameProto.BGameInit.newBuilder(bGameInit_).mergeFrom(value).buildPartial();
          } else {
            bGameInit_ = value;
          }
          onChanged();
        } else {
          bGameInitBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public Builder clearBGameInit() {
        if (bGameInitBuilder_ == null) {
          bGameInit_ = null;
          onChanged();
        } else {
          bGameInit_ = null;
          bGameInitBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public GameProto.BGameInit.Builder getBGameInitBuilder() {
        
        onChanged();
        return getBGameInitFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      public GameProto.BGameInitOrBuilder getBGameInitOrBuilder() {
        if (bGameInitBuilder_ != null) {
          return bGameInitBuilder_.getMessageOrBuilder();
        } else {
          return bGameInit_ == null ?
              GameProto.BGameInit.getDefaultInstance() : bGameInit_;
        }
      }
      /**
       * <pre>
       ** 游戏初始化信息 
       * </pre>
       *
       * <code>.lspb.BGameInit bGameInit = 1001;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.BGameInit, GameProto.BGameInit.Builder, GameProto.BGameInitOrBuilder>
          getBGameInitFieldBuilder() {
        if (bGameInitBuilder_ == null) {
          bGameInitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.BGameInit, GameProto.BGameInit.Builder, GameProto.BGameInitOrBuilder>(
                  getBGameInit(),
                  getParentForChildren(),
                  isClean());
          bGameInit_ = null;
        }
        return bGameInitBuilder_;
      }

      private GameProto.BGameStart bGameStart_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.BGameStart, GameProto.BGameStart.Builder, GameProto.BGameStartOrBuilder> bGameStartBuilder_;
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public boolean hasBGameStart() {
        return bGameStartBuilder_ != null || bGameStart_ != null;
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public GameProto.BGameStart getBGameStart() {
        if (bGameStartBuilder_ == null) {
          return bGameStart_ == null ? GameProto.BGameStart.getDefaultInstance() : bGameStart_;
        } else {
          return bGameStartBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public Builder setBGameStart(GameProto.BGameStart value) {
        if (bGameStartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bGameStart_ = value;
          onChanged();
        } else {
          bGameStartBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public Builder setBGameStart(
          GameProto.BGameStart.Builder builderForValue) {
        if (bGameStartBuilder_ == null) {
          bGameStart_ = builderForValue.build();
          onChanged();
        } else {
          bGameStartBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public Builder mergeBGameStart(GameProto.BGameStart value) {
        if (bGameStartBuilder_ == null) {
          if (bGameStart_ != null) {
            bGameStart_ =
              GameProto.BGameStart.newBuilder(bGameStart_).mergeFrom(value).buildPartial();
          } else {
            bGameStart_ = value;
          }
          onChanged();
        } else {
          bGameStartBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public Builder clearBGameStart() {
        if (bGameStartBuilder_ == null) {
          bGameStart_ = null;
          onChanged();
        } else {
          bGameStart_ = null;
          bGameStartBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public GameProto.BGameStart.Builder getBGameStartBuilder() {
        
        onChanged();
        return getBGameStartFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      public GameProto.BGameStartOrBuilder getBGameStartOrBuilder() {
        if (bGameStartBuilder_ != null) {
          return bGameStartBuilder_.getMessageOrBuilder();
        } else {
          return bGameStart_ == null ?
              GameProto.BGameStart.getDefaultInstance() : bGameStart_;
        }
      }
      /**
       * <pre>
       ** 游戏正式开始推送 
       * </pre>
       *
       * <code>.lspb.BGameStart bGameStart = 1002;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.BGameStart, GameProto.BGameStart.Builder, GameProto.BGameStartOrBuilder>
          getBGameStartFieldBuilder() {
        if (bGameStartBuilder_ == null) {
          bGameStartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.BGameStart, GameProto.BGameStart.Builder, GameProto.BGameStartOrBuilder>(
                  getBGameStart(),
                  getParentForChildren(),
                  isClean());
          bGameStart_ = null;
        }
        return bGameStartBuilder_;
      }

      private GameProto.BGameFrame bGameFrame_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.BGameFrame, GameProto.BGameFrame.Builder, GameProto.BGameFrameOrBuilder> bGameFrameBuilder_;
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public boolean hasBGameFrame() {
        return bGameFrameBuilder_ != null || bGameFrame_ != null;
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public GameProto.BGameFrame getBGameFrame() {
        if (bGameFrameBuilder_ == null) {
          return bGameFrame_ == null ? GameProto.BGameFrame.getDefaultInstance() : bGameFrame_;
        } else {
          return bGameFrameBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public Builder setBGameFrame(GameProto.BGameFrame value) {
        if (bGameFrameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bGameFrame_ = value;
          onChanged();
        } else {
          bGameFrameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public Builder setBGameFrame(
          GameProto.BGameFrame.Builder builderForValue) {
        if (bGameFrameBuilder_ == null) {
          bGameFrame_ = builderForValue.build();
          onChanged();
        } else {
          bGameFrameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public Builder mergeBGameFrame(GameProto.BGameFrame value) {
        if (bGameFrameBuilder_ == null) {
          if (bGameFrame_ != null) {
            bGameFrame_ =
              GameProto.BGameFrame.newBuilder(bGameFrame_).mergeFrom(value).buildPartial();
          } else {
            bGameFrame_ = value;
          }
          onChanged();
        } else {
          bGameFrameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public Builder clearBGameFrame() {
        if (bGameFrameBuilder_ == null) {
          bGameFrame_ = null;
          onChanged();
        } else {
          bGameFrame_ = null;
          bGameFrameBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public GameProto.BGameFrame.Builder getBGameFrameBuilder() {
        
        onChanged();
        return getBGameFrameFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      public GameProto.BGameFrameOrBuilder getBGameFrameOrBuilder() {
        if (bGameFrameBuilder_ != null) {
          return bGameFrameBuilder_.getMessageOrBuilder();
        } else {
          return bGameFrame_ == null ?
              GameProto.BGameFrame.getDefaultInstance() : bGameFrame_;
        }
      }
      /**
       * <pre>
       ** 游戏逻辑帧操作 
       * </pre>
       *
       * <code>.lspb.BGameFrame bGameFrame = 1003;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameProto.BGameFrame, GameProto.BGameFrame.Builder, GameProto.BGameFrameOrBuilder>
          getBGameFrameFieldBuilder() {
        if (bGameFrameBuilder_ == null) {
          bGameFrameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameProto.BGameFrame, GameProto.BGameFrame.Builder, GameProto.BGameFrameOrBuilder>(
                  getBGameFrame(),
                  getParentForChildren(),
                  isClean());
          bGameFrame_ = null;
        }
        return bGameFrameBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:lspb.SrvRes)
    }

    // @@protoc_insertion_point(class_scope:lspb.SrvRes)
    private static final SrvRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SrvRes();
    }

    public static SrvRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SrvRes>
        PARSER = new com.google.protobuf.AbstractParser<SrvRes>() {
      public SrvRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SrvRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SrvRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SrvRes> getParserForType() {
      return PARSER;
    }

    public SrvRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lspb_SrvRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lspb_SrvRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014srvRes.proto\022\004lspb\032\014lsEnum.proto\032\017game" +
      "Proto.proto\"\237\002\n\006SrvRes\022\"\n\010methodId\030\001 \001(\016" +
      "2\020.lspb.SrvMsgType\022\034\n\006result\030\002 \001(\0162\014.lsp" +
      "b.Result\022\016\n\006errStr\030\003 \001(\t\022(\n\014srvEnterRoom" +
      "\030e \001(\0132\022.lspb.SrvEnterRoom\022&\n\013srvInitOve" +
      "r\030f \001(\0132\021.lspb.SrvInitOver\022#\n\tbGameInit\030" +
      "\351\007 \001(\0132\017.lspb.BGameInit\022%\n\nbGameStart\030\352\007" +
      " \001(\0132\020.lspb.BGameStart\022%\n\nbGameFrame\030\353\007 " +
      "\001(\0132\020.lspb.BGameFrame*v\n\nSrvMsgType\022\023\n\017e" +
      "rrorServerType\020\000\022\020\n\014srvEnterRoom\020e\022\017\n\013sr",
      "vInitOver\020f\022\016\n\tbGameInit\020\351\007\022\017\n\nbGameStar" +
      "t\020\352\007\022\017\n\nbGameFrame\020\353\007B\037\n\020org.bro.lssrv.p" +
      "bB\013SrvResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          LsEnum.getDescriptor(),
          GameProto.getDescriptor(),
        }, assigner);
    internal_static_lspb_SrvRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lspb_SrvRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lspb_SrvRes_descriptor,
        new String[] { "MethodId", "Result", "ErrStr", "SrvEnterRoom", "SrvInitOver", "BGameInit", "BGameStart", "BGameFrame", });
    LsEnum.getDescriptor();
    GameProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
